In [1]:
import pandas as pd

In [2]:
ventas = pd.read_csv("ventas.csv")

In [3]:
ventas.head()

        fecha  id_cliente             producto  cantidad  precio_unitario
0  2026-09-01           1    Mouse inalámbrico         2            18000
1  2026-09-01           2     Teclado mecánico         1            42000
2  2026-09-02           3          Auriculares         1            35000
3  2026-09-02           1               Webcam         1            48000
4  2026-09-03           4  Monitor 24 pulgadas         1           210000

In [4]:
clientes = pd.read_json("clientes.json")

In [5]:
clientes

   id_cliente           nombre         ciudad                        email
0           1        Ana López   Buenos Aires        ana.lopez@example.com
1           2       Bruno Díaz        Córdoba       bruno.diaz@example.com
2           3      Carla Gómez        Rosario      carla.gomez@example.com
3           4  Diego Fernández        Mendoza  diego.fernandez@example.com
4           5       Elena Ruiz       La Plata       elena.ruiz@example.com
5           6    Facundo Pérez  Mar del Plata    facundo.perez@example.com

In [6]:
len(clientes)

6

In [7]:
inventario=pd.read_excel("inventario.xlsx")

In [8]:
inventario

              producto    categoria  stock_disponible  precio_unitario
0    Mouse inalámbrico  Periféricos                25            18000
1     Teclado mecánico  Periféricos                14            42000
2          Auriculares        Audio                18            35000
3               Webcam        Video                11            48000
4  Monitor 24 pulgadas    Monitores                 7           210000
5       Notebook Stand   Accesorios                20            26000
6           Cable HDMI   Accesorios                35            12000
7            Hub USB-C   Accesorios                16            30000

In [9]:
inventario["stock_disponible"].mean()

np.float64(18.25)